// <auto-generated />
using System;
using Kodlama.Io.Devs.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kodlama.Io.Devs.Persistence.Migrations
{
    [DbContext(typeof(BaseDbContext))]
    [Migration("20220911125230_Added_Technology")]
    partial class Added_Technology
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Kodlama.Io.Devs.Domain.Entities.ProgrammingLanguage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("ProgrammingLanguages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("477f1210-db3f-43fc-8403-cf018755aa41"),
                            Name = "C#"
                        },
                        new
                        {
                            Id = new Guid("e10194ea-85ec-4c51-a086-3ac7820f3594"),
                            Name = "Java"
                        });
                });

            modelBuilder.Entity("Kodlama.Io.Devs.Domain.Entities.Technology", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<Guid>("ProgrammingLanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProgrammingLanguageId");

                    b.ToTable("Technologies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b9516f6b-7cc5-4be3-8c11-f8e6e9e7754f"),
                            Name = "WPF",
                            ProgrammingLanguageId = new Guid("477f1210-db3f-43fc-8403-cf018755aa41")
                        },
                        new
                        {
                            Id = new Guid("35a5b5aa-f81a-4208-ad76-054a5bf58686"),
                            Name = ".NET",
                            ProgrammingLanguageId = new Guid("477f1210-db3f-43fc-8403-cf018755aa41")
                        },
                        new
                        {
                            Id = new Guid("37edf730-6ae7-4532-8233-138a1f5c9d0c"),
                            Name = "Spring",
                            ProgrammingLanguageId = new Guid("e10194ea-85ec-4c51-a086-3ac7820f3594")
                        });
                });

            modelBuilder.Entity("Kodlama.Io.Devs.Domain.Entities.Technology", b =>
                {
                    b.HasOne("Kodlama.Io.Devs.Domain.Entities.ProgrammingLanguage", "ProgrammingLanguage")
                        .WithMany("Technologies")
                        .HasForeignKey("ProgrammingLanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProgrammingLanguage");
                });

            modelBuilder.Entity("Kodlama.Io.Devs.Domain.Entities.ProgrammingLanguage", b =>
                {
                    b.Navigation("Technologies");
                });
#pragma warning restore 612, 618
        }
    }
}
